CREATE TABLE "county" (
	"state_county_code" text PRIMARY KEY NOT NULL,
	"state_code" integer NOT NULL,
	"county_code" integer NOT NULL,
	"state" text NOT NULL,
	"county_name" text NOT NULL,
	"city" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pollution_data" (
	"id" text PRIMARY KEY NOT NULL,
	"state_county_code" text NOT NULL,
	"date_local" timestamp NOT NULL,
	"no2_units" text NOT NULL,
	"no2_mean" real NOT NULL,
	"no2_1st_max_value" real NOT NULL,
	"no2_1st_max_hour" integer NOT NULL,
	"no2_aqi" integer,
	"o3_units" text NOT NULL,
	"o3_mean" real NOT NULL,
	"o3_1st_max_value" real NOT NULL,
	"o3_1st_max_hour" integer NOT NULL,
	"o3_aqi" integer,
	"so2_units" text NOT NULL,
	"so2_mean" real NOT NULL,
	"so2_1st_max_value" real NOT NULL,
	"so2_1st_max_hour" integer,
	"so2_aqi" integer,
	"co_units" text NOT NULL,
	"co_mean" real NOT NULL,
	"co_1st_max_value" real NOT NULL,
	"co_1st_max_hour" integer,
	"co_aqi" integer
);
--> statement-breakpoint
CREATE TABLE "subscribers" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"subscribed" boolean DEFAULT true NOT NULL,
	CONSTRAINT "subscribers_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "hazard_data" (
	"oid_" integer,
	"nri_id" text,
	"state" text,
	"stateabbrv" text,
	"statefips" text,
	"county" text,
	"countytype" text,
	"countyfips" text,
	"stcofips" text,
	"population" integer,
	"buildvalue" double precision,
	"agrivalue" double precision,
	"area" double precision,
	"risk_value" double precision,
	"risk_score" double precision,
	"risk_ratng" text,
	"risk_spctl" double precision,
	"eal_score" double precision,
	"eal_ratng" text,
	"eal_spctl" double precision,
	"eal_valt" double precision,
	"eal_valb" double precision,
	"eal_valp" double precision,
	"eal_valpe" double precision,
	"eal_vala" double precision,
	"alr_valb" double precision,
	"alr_valp" double precision,
	"alr_vala" double precision,
	"alr_npctl" double precision,
	"alr_vra_npctl" double precision,
	"sovi_score" double precision,
	"sovi_ratng" text,
	"sovi_spctl" double precision,
	"resl_score" double precision,
	"resl_ratng" text,
	"resl_spctl" double precision,
	"resl_value" double precision,
	"crf_value" double precision,
	"avln_evnts" double precision,
	"avln_afreq" double precision,
	"avln_exp_area" double precision,
	"avln_expb" double precision,
	"avln_expp" double precision,
	"avln_exppe" double precision,
	"avln_expt" double precision,
	"avln_hlrb" double precision,
	"avln_hlrp" double precision,
	"avln_hlrr" text,
	"avln_ealb" double precision,
	"avln_ealp" double precision,
	"avln_ealpe" double precision,
	"avln_ealt" double precision,
	"avln_eals" double precision,
	"avln_ealr" text,
	"avln_alrb" double precision,
	"avln_alrp" double precision,
	"avln_alr_npctl" double precision,
	"avln_riskv" double precision,
	"avln_risks" double precision,
	"avln_riskr" text,
	"cfld_evnts" double precision,
	"cfld_afreq" double precision,
	"cfld_exp_area" double precision,
	"cfld_expb" double precision,
	"cfld_expp" double precision,
	"cfld_exppe" double precision,
	"cfld_expt" double precision,
	"cfld_hlrb" double precision,
	"cfld_hlrp" double precision,
	"cfld_hlrr" text,
	"cfld_ealb" double precision,
	"cfld_ealp" double precision,
	"cfld_ealpe" double precision,
	"cfld_ealt" double precision,
	"cfld_eals" double precision,
	"cfld_ealr" text,
	"cfld_alrb" double precision,
	"cfld_alrp" double precision,
	"cfld_alr_npctl" double precision,
	"cfld_riskv" double precision,
	"cfld_risks" double precision,
	"cfld_riskr" text,
	"cwav_evnts" double precision,
	"cwav_afreq" double precision,
	"cwav_exp_area" double precision,
	"cwav_expb" double precision,
	"cwav_expp" double precision,
	"cwav_exppe" double precision,
	"cwav_expa" double precision,
	"cwav_expt" double precision,
	"cwav_hlrb" double precision,
	"cwav_hlrp" double precision,
	"cwav_hlra" double precision,
	"cwav_hlrr" text,
	"cwav_ealb" double precision,
	"cwav_ealp" double precision,
	"cwav_ealpe" double precision,
	"cwav_eala" double precision,
	"cwav_ealt" double precision,
	"cwav_eals" double precision,
	"cwav_ealr" text,
	"cwav_alrb" double precision,
	"cwav_alrp" double precision,
	"cwav_alra" double precision,
	"cwav_alr_npctl" double precision,
	"cwav_riskv" double precision,
	"cwav_risks" double precision,
	"cwav_riskr" text,
	"drgt_evnts" double precision,
	"drgt_afreq" double precision,
	"drgt_exp_area" double precision,
	"drgt_expa" double precision,
	"drgt_expt" double precision,
	"drgt_hlra" double precision,
	"drgt_hlrr" text,
	"drgt_eala" double precision,
	"drgt_ealt" double precision,
	"drgt_eals" double precision,
	"drgt_ealr" text,
	"drgt_alra" double precision,
	"drgt_alr_npctl" double precision,
	"drgt_riskv" double precision,
	"drgt_risks" double precision,
	"drgt_riskr" text,
	"erqk_evnts" double precision,
	"erqk_afreq" double precision,
	"erqk_exp_area" double precision,
	"erqk_expb" double precision,
	"erqk_expp" double precision,
	"erqk_exppe" double precision,
	"erqk_expt" double precision,
	"erqk_hlrb" double precision,
	"erqk_hlrp" double precision,
	"erqk_hlrr" text,
	"erqk_ealb" double precision,
	"erqk_ealp" double precision,
	"erqk_ealpe" double precision,
	"erqk_ealt" double precision,
	"erqk_eals" double precision,
	"erqk_ealr" text,
	"erqk_alrb" double precision,
	"erqk_alrp" double precision,
	"erqk_alr_npctl" double precision,
	"erqk_riskv" double precision,
	"erqk_risks" double precision,
	"erqk_riskr" text,
	"hail_evnts" double precision,
	"hail_afreq" double precision,
	"hail_exp_area" double precision,
	"hail_expb" double precision,
	"hail_expp" double precision,
	"hail_exppe" double precision,
	"hail_expa" double precision,
	"hail_expt" double precision,
	"hail_hlrb" double precision,
	"hail_hlrp" double precision,
	"hail_hlra" double precision,
	"hail_hlrr" text,
	"hail_ealb" double precision,
	"hail_ealp" double precision,
	"hail_ealpe" double precision,
	"hail_eala" double precision,
	"hail_ealt" double precision,
	"hail_eals" double precision,
	"hail_ealr" text,
	"hail_alrb" double precision,
	"hail_alrp" double precision,
	"hail_alra" double precision,
	"hail_alr_npctl" double precision,
	"hail_riskv" double precision,
	"hail_risks" double precision,
	"hail_riskr" text,
	"hwav_evnts" double precision,
	"hwav_afreq" double precision,
	"hwav_exp_area" double precision,
	"hwav_expb" double precision,
	"hwav_expp" double precision,
	"hwav_exppe" double precision,
	"hwav_expa" double precision,
	"hwav_expt" double precision,
	"hwav_hlrb" double precision,
	"hwav_hlrp" double precision,
	"hwav_hlra" double precision,
	"hwav_hlrr" text,
	"hwav_ealb" double precision,
	"hwav_ealp" double precision,
	"hwav_ealpe" double precision,
	"hwav_eala" double precision,
	"hwav_ealt" double precision,
	"hwav_eals" double precision,
	"hwav_ealr" text,
	"hwav_alrb" double precision,
	"hwav_alrp" double precision,
	"hwav_alra" double precision,
	"hwav_alr_npctl" double precision,
	"hwav_riskv" double precision,
	"hwav_risks" double precision,
	"hwav_riskr" text,
	"hrcn_evnts" double precision,
	"hrcn_afreq" double precision,
	"hrcn_exp_area" double precision,
	"hrcn_expb" double precision,
	"hrcn_expp" double precision,
	"hrcn_exppe" double precision,
	"hrcn_expa" double precision,
	"hrcn_expt" double precision,
	"hrcn_hlrb" double precision,
	"hrcn_hlrp" double precision,
	"hrcn_hlra" double precision,
	"hrcn_hlrr" text,
	"hrcn_ealb" double precision,
	"hrcn_ealp" double precision,
	"hrcn_ealpe" double precision,
	"hrcn_eala" double precision,
	"hrcn_ealt" double precision,
	"hrcn_eals" double precision,
	"hrcn_ealr" text,
	"hrcn_alrb" double precision,
	"hrcn_alrp" double precision,
	"hrcn_alra" double precision,
	"hrcn_alr_npctl" double precision,
	"hrcn_riskv" double precision,
	"hrcn_risks" double precision,
	"hrcn_riskr" text,
	"istm_evnts" double precision,
	"istm_afreq" double precision,
	"istm_exp_area" double precision,
	"istm_expb" double precision,
	"istm_expp" double precision,
	"istm_exppe" double precision,
	"istm_expt" double precision,
	"istm_hlrb" double precision,
	"istm_hlrp" double precision,
	"istm_hlrr" text,
	"istm_ealb" double precision,
	"istm_ealp" double precision,
	"istm_ealpe" double precision,
	"istm_ealt" double precision,
	"istm_eals" double precision,
	"istm_ealr" text,
	"istm_alrb" double precision,
	"istm_alrp" double precision,
	"istm_alr_npctl" double precision,
	"istm_riskv" double precision,
	"istm_risks" double precision,
	"istm_riskr" text,
	"lnds_evnts" double precision,
	"lnds_afreq" double precision,
	"lnds_exp_area" double precision,
	"lnds_expb" double precision,
	"lnds_expp" double precision,
	"lnds_exppe" double precision,
	"lnds_expt" double precision,
	"lnds_hlrb" double precision,
	"lnds_hlrp" double precision,
	"lnds_hlrr" text,
	"lnds_ealb" double precision,
	"lnds_ealp" double precision,
	"lnds_ealpe" double precision,
	"lnds_ealt" double precision,
	"lnds_eals" double precision,
	"lnds_ealr" text,
	"lnds_alrb" double precision,
	"lnds_alrp" double precision,
	"lnds_alr_npctl" double precision,
	"lnds_riskv" double precision,
	"lnds_risks" double precision,
	"lnds_riskr" text,
	"ltng_evnts" double precision,
	"ltng_afreq" double precision,
	"ltng_exp_area" double precision,
	"ltng_expb" double precision,
	"ltng_expp" double precision,
	"ltng_exppe" double precision,
	"ltng_expt" double precision,
	"ltng_hlrb" double precision,
	"ltng_hlrp" double precision,
	"ltng_hlrr" text,
	"ltng_ealb" double precision,
	"ltng_ealp" double precision,
	"ltng_ealpe" double precision,
	"ltng_ealt" double precision,
	"ltng_eals" double precision,
	"ltng_ealr" text,
	"ltng_alrb" double precision,
	"ltng_alrp" double precision,
	"ltng_alr_npctl" double precision,
	"ltng_riskv" double precision,
	"ltng_risks" double precision,
	"ltng_riskr" text,
	"rfld_evnts" double precision,
	"rfld_afreq" double precision,
	"rfld_exp_area" double precision,
	"rfld_expb" double precision,
	"rfld_expp" double precision,
	"rfld_exppe" double precision,
	"rfld_expa" double precision,
	"rfld_expt" double precision,
	"rfld_hlrb" double precision,
	"rfld_hlrp" double precision,
	"rfld_hlra" double precision,
	"rfld_hlrr" text,
	"rfld_ealb" double precision,
	"rfld_ealp" double precision,
	"rfld_ealpe" double precision,
	"rfld_eala" double precision,
	"rfld_ealt" double precision,
	"rfld_eals" double precision,
	"rfld_ealr" text,
	"rfld_alrb" double precision,
	"rfld_alrp" double precision,
	"rfld_alra" double precision,
	"rfld_alr_npctl" double precision,
	"rfld_riskv" double precision,
	"rfld_risks" double precision,
	"rfld_riskr" text,
	"swnd_evnts" double precision,
	"swnd_afreq" double precision,
	"swnd_exp_area" double precision,
	"swnd_expb" double precision,
	"swnd_expp" double precision,
	"swnd_exppe" double precision,
	"swnd_expa" double precision,
	"swnd_expt" double precision,
	"swnd_hlrb" double precision,
	"swnd_hlrp" double precision,
	"swnd_hlra" double precision,
	"swnd_hlrr" text,
	"swnd_ealb" double precision,
	"swnd_ealp" double precision,
	"swnd_ealpe" double precision,
	"swnd_eala" double precision,
	"swnd_ealt" double precision,
	"swnd_eals" double precision,
	"swnd_ealr" text,
	"swnd_alrb" double precision,
	"swnd_alrp" double precision,
	"swnd_alra" double precision,
	"swnd_alr_npctl" double precision,
	"swnd_riskv" double precision,
	"swnd_risks" double precision,
	"swnd_riskr" text,
	"trnd_evnts" double precision,
	"trnd_afreq" double precision,
	"trnd_exp_area" double precision,
	"trnd_expb" double precision,
	"trnd_expp" double precision,
	"trnd_exppe" double precision,
	"trnd_expa" double precision,
	"trnd_expt" double precision,
	"trnd_hlrb" double precision,
	"trnd_hlrp" double precision,
	"trnd_hlra" double precision,
	"trnd_hlrr" text,
	"trnd_ealb" double precision,
	"trnd_ealp" double precision,
	"trnd_ealpe" double precision,
	"trnd_eala" double precision,
	"trnd_ealt" double precision,
	"trnd_eals" double precision,
	"trnd_ealr" text,
	"trnd_alrb" double precision,
	"trnd_alrp" double precision,
	"trnd_alra" double precision,
	"trnd_alr_npctl" double precision,
	"trnd_riskv" double precision,
	"trnd_risks" double precision,
	"trnd_riskr" text,
	"tsun_evnts" double precision,
	"tsun_afreq" double precision,
	"tsun_exp_area" double precision,
	"tsun_expb" double precision,
	"tsun_expp" double precision,
	"tsun_exppe" double precision,
	"tsun_expt" double precision,
	"tsun_hlrb" double precision,
	"tsun_hlrp" double precision,
	"tsun_hlrr" text,
	"tsun_ealb" double precision,
	"tsun_ealp" double precision,
	"tsun_ealpe" double precision,
	"tsun_ealt" double precision,
	"tsun_eals" double precision,
	"tsun_ealr" text,
	"tsun_alrb" double precision,
	"tsun_alrp" double precision,
	"tsun_alr_npctl" double precision,
	"tsun_riskv" double precision,
	"tsun_risks" double precision,
	"tsun_riskr" text,
	"vlcn_evnts" double precision,
	"vlcn_afreq" double precision,
	"vlcn_exp_area" double precision,
	"vlcn_expb" double precision,
	"vlcn_expp" double precision,
	"vlcn_exppe" double precision,
	"vlcn_expt" double precision,
	"vlcn_hlrb" double precision,
	"vlcn_hlrp" double precision,
	"vlcn_hlrr" text,
	"vlcn_ealb" double precision,
	"vlcn_ealp" double precision,
	"vlcn_ealpe" double precision,
	"vlcn_ealt" double precision,
	"vlcn_eals" double precision,
	"vlcn_ealr" text,
	"vlcn_alrb" double precision,
	"vlcn_alrp" double precision,
	"vlcn_alr_npctl" double precision,
	"vlcn_riskv" double precision,
	"vlcn_risks" double precision,
	"vlcn_riskr" text,
	"wfir_evnts" double precision,
	"wfir_afreq" double precision,
	"wfir_exp_area" double precision,
	"wfir_expb" double precision,
	"wfir_expp" double precision,
	"wfir_exppe" double precision,
	"wfir_expa" double precision,
	"wfir_expt" double precision,
	"wfir_hlrb" double precision,
	"wfir_hlrp" double precision,
	"wfir_hlra" double precision,
	"wfir_hlrr" text,
	"wfir_ealb" double precision,
	"wfir_ealp" double precision,
	"wfir_ealpe" double precision,
	"wfir_eala" double precision,
	"wfir_ealt" double precision,
	"wfir_eals" double precision,
	"wfir_ealr" text,
	"wfir_alrb" double precision,
	"wfir_alrp" double precision,
	"wfir_alra" double precision,
	"wfir_alr_npctl" double precision,
	"wfir_riskv" double precision,
	"wfir_risks" double precision,
	"wfir_riskr" text,
	"wntw_evnts" double precision,
	"wntw_afreq" double precision,
	"wntw_exp_area" double precision,
	"wntw_expb" double precision,
	"wntw_expp" double precision,
	"wntw_exppe" double precision,
	"wntw_expa" double precision,
	"wntw_expt" double precision,
	"wntw_hlrb" double precision,
	"wntw_hlrp" double precision,
	"wntw_hlra" double precision,
	"wntw_hlrr" text,
	"wntw_ealb" double precision,
	"wntw_ealp" double precision,
	"wntw_ealpe" double precision,
	"wntw_eala" double precision,
	"wntw_ealt" double precision,
	"wntw_eals" double precision,
	"wntw_ealr" text,
	"wntw_alrb" double precision,
	"wntw_alrp" double precision,
	"wntw_alra" double precision,
	"wntw_alr_npctl" double precision,
	"wntw_riskv" double precision,
	"wntw_risks" double precision,
	"wntw_riskr" text,
	"nri_ver" text
);
--> statement-breakpoint
ALTER TABLE "pollution_data" ADD CONSTRAINT "pollution_data_state_county_code_county_state_county_code_fk" FOREIGN KEY ("state_county_code") REFERENCES "public"."county"("state_county_code") ON DELETE cascade ON UPDATE no action;